=== StarBit23/DAM/4.AccesoDatos/JUNIO/parserDomMavenJorgeOrtega/dibujo.dtd
<!ELEMENT dibujo (poligono*)>
<!ELEMENT poligono (vertice, vertice, vertice+)>
<!ELEMENT vertice (x, y)>
<!ELEMENT x (#PCDATA) >
<!ELEMENT y (#PCDATA) >
<!ATTLIST poligono nombre CDATA #REQUIRED>
<!ATTLIST vertice nombre CDATA #IMPLIED>

=== StarBit23/DAM/4.AccesoDatos/JUNIO/parserDomMavenJorgeOrtega/dibujo.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE dibujo SYSTEM "dibujo.dtd">
<dibujo>
	<poligono nombre="mi_poli">
		<vertice nombre="mi_verti">
			<x>0</x>
			<y>0</y>
		</vertice>
		<vertice>
			<x>0</x>
			<y>2</y>
		</vertice>
		<vertice>
			<x>2</x>
			<y>0</y>
		</vertice>
	</poligono>
</dibujo>
