=== StarBit23/DAM/4.AccesoDatos/Tema1/Ej1 profe/factura.dtd
<!ELEMENT factura (cliente, direccion, productos)>
<!ELEMENT cliente (nombre, apellido, email, telefono, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (nombreVia, tipoVia, localidad, cp)>
<!ELEMENT nombreVia (#PCDATA)>
<!ELEMENT tipoVia (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ATTLIST factura id CDATA #REQUIRED>
<!ATTLIST factura fecha CDATA #IMPLIED>
<!ATTLIST cliente id CDATA #REQUIRED>
<!ELEMENT productos (producto*)>
<!ELEMENT producto (nombre, descripcion, precio)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST producto id CDATA #REQUIRED>
<!ATTLIST producto cantidad CDATA #REQUIRED>

=== StarBit23/DAM/4.AccesoDatos/TEMA 1/Tema1/Ej1 profe/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">
<factura id="102-2022" fecha="19/10/2022">
    <cliente id="234234">
        <nombre>Juan</nombre>
        <apellido>Nadie</apellido>
        <email>juan@sincorreo.com</email>
        <telefono>+34-555-677-890</telefono>
        <direccion>
            <nombreVia>de la Estación</nombreVia>
            <tipoVia>Paseo</tipoVia>
            <localidad>Jaén</localidad>
            <cp>23008</cp>
        </direccion>
    </cliente>
    <direccion>
        <nombreVia>del Percebe</nombreVia>
        <tipoVia>Rue</tipoVia>
        <localidad>Madrid</localidad>
        <cp>28001</cp>
    </direccion>
    <productos>
        <producto id="12312" cantidad="2">
            <nombre>Teclado USB</nombre>
            <descripcion>Teclado gaming retroiluminado</descripcion>
            <precio>36€</precio>
        </producto>
        <producto id="12312" cantidad="2">
            <nombre>Teclado USB</nombre>
            <descripcion>Teclado gaming retroiluminado</descripcion>
            <precio>36€</precio>
        </producto>
    </productos>
</factura>
