=== StarBit23/DAM/4.AccesoDatos/TEMA 1/Tema1/Ejercicio1/datos.dtd
<!ELEMENT persona (nombre, apellidos, direccion, numero, email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (cp,ciudad,tipo_via,via,numero,portal,puerta)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT tipo_via (#PCDATA)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT portal (#PCDATA)>
<!ELEMENT puerta (#PCDATA)>

=== StarBit23/DAM/4.AccesoDatos/TEMA 1/Tema1/Ejercicio1/datos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE persona SYSTEM "datos.dtd">
<persona>
    <nombre>Pepe</nombre>
    <apellidos>García Fernández</apellidos>
    <direccion>
        <cp>23008</cp>
        <ciudad>Jaén</ciudad>
        <tipo_via>Paseo</tipo_via>
        <via>Estación</via>
        <numero>44</numero>
        <portal>5</portal>
        <puerta>5</puerta>
    </direccion>
    <numero>555123456</numero>
    <email>pepe@sincorreo.com</email>
</persona>
